name: Debug
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: debug
      run: cat .git/config
