name: Debug
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: dovecot/documentation
        path: dovecot-documentation
        ssh-key: ${{ secrets.DOVECOT }}
    - name: debug
      run: |
        echo .git/config:
        cat .git/config
        echo dovecot-documentation/.git/config:
        cat dovecot-documentation/.git/config
